Fonction de récupération d'un message
Virtual-Royaume/Royaume-Discord-Bot pull request #217
Opened 2023-06-07 11:57 UTC by Steellgold

- Close #211

2023-06-07 20:39 UTC, Bluzzi requested changes
Je me demande si le fichier utilitaire `message` n'aurait pas sa place au côté des fichiers utilitaires dans `/utils/function` ?

2023-06-07 21:38 UTC, Unarray commented on src/utils/message/message.test.ts
> +  });
Ne serait-il pas plus judicieux de déplacer ces fonctions dans [`/utils/discord/`](https://github.com/Virtual-Royaume/Royaume-Discord-Bot/tree/main/src/utils/discord/) ?
Car si on déplace cette fonction dans [`/utils/function/`](https://github.com/Virtual-Royaume/Royaume-Discord-Bot/tree/main/src/utils/function/) il faudra aussi déplacer ce qu'il y a dans [`/utils/discord/`](https://github.com/Virtual-Royaume/Royaume-Discord-Bot/tree/main/src/utils/discord/) pour que ca soit un minimum cohérent.

2023-06-07 21:43 UTC, Bluzzi commented on src/utils/message/message.test.ts
> +  });
Dans `/utils/discord` c'est destiné aux fonctions qui utilise directement l'API Discord, la ou `/utils/function` est fait pour des fonctions totalement native à JS et qui peuvent donc être testé de manière isolé.

2023-06-07 21:53 UTC, Unarray commented on src/utils/message/message.test.ts
> +  });
Effectivement, je parlais surtout pour la future fonction de récupération d'un message

2023-06-07 22:51 UTC, Steellgold commented
![image](https://github.com/Virtual-Royaume/Royaume-Discord-Bot/assets/51505384/1b8628f5-cada-43c4-931d-70c6ca33e9e1)

2023-06-25 22:28 UTC, Bluzzi requested changes

2023-06-25 22:28 UTC, Bluzzi commented on src/utils/message/message.util.ts
> +  const messageId = ids[2];
La manière de parse est pourrait être amélioré :
```ts
const content = `
	Hello World!
 	https://canary.discord.com/channels/732251741999071303/786216771723198514/803532192793493544
  	are you ok ?
   	https://canary.discord.com/channels/732251741999071303/786216771723198514/803532192793493544
`;

const matchs = [...content.matchAll(/\/\d+\/\d+\/\d+/g)].map(element => {
  const [guildID, channelID, messageID] = [...element[0].matchAll(/\d+/g)].map(e => e[0]);
  
  return { guildID, channelID, messageID };
});

console.log(matchs);
```

2023-06-25 22:34 UTC, Bluzzi requested changes

2023-06-25 22:34 UTC, Bluzzi commented on src/utils/message/_test/contains-discord-link.test.ts
> +    ).toBe(true);
En anglais les tests

2024-02-17 18:31 UTC, Arcoz0308 commented
Que manque il a ce pr ? @Bluzzi

2024-02-17 21:04 UTC, Bluzzi commented
Certainement la résolution des reviews ouvertes, bien que des nouveaux commits ont vu le jour depuis celle-ci. On a pas eu de nouvelle de Gaëtan et il n'a pas actualisé le status des reviews.

2024-02-28 22:34 UTC, Steellgold commented
> Certainement la résolution des reviews ouvertes, bien que des nouveaux commits ont vu le jour depuis celle-ci. On a pas eu de nouvelle de Gaëtan et il n'a pas actualisé le status des reviews.

Je n'avais pas répondu / resolve mais j'avais commit les changements.

2024-07-13 21:51 UTC, closed without merging