Mode de développement
Virtual-Royaume/Royaume-Discord-Bot pull request #75
Opened 2022-07-06 13:35 UTC by Steellgold

Pour l'instant j'ai désactivé les statistiques des messages, ainsi que du temps de vocal, si d'autres choses à désactiver (à voir si il y a d'autres choses)

Close #58

2022-07-06 19:38 UTC, Bluzzi commented
Cette PR est intéressante @Virtual-Royaume/royaume-dev 

Il s'agit des fonctionnalités qui sont désactivé ou modifié lorsqu'on lance le bot avec la commande ``npm run dev``, pour éviter les requête en double à la DB, les problèmes en mode développement du au fait que plusieurs instances tourne, etc.

N'hésitez pas à laisser un commentaire sur les fonctionnalités qui vous semble pertinente à désactiver/modifier.

2022-07-06 19:48 UTC, Bluzzi commented on package.json
> +    "dev": "cross-env NODE_ENV=dev nodemon --exec ts-node ./src/Client.ts",
Ici tu utilise un package supplémentaire ainsi que des variables d'environnement pour ceci, je préférerais une approche plus basique pour ce systeme : préciser simplement un argument (exemple : ``nodemon --exec ts-node ./src/Client.ts dev``) puis vérifier celui-ci via ``process.argv.includes("dev")``

2022-07-06 19:48 UTC, Bluzzi commented on src/Client.ts
> +    }
Cette fonction devrait fonctionner avec le nouveau systeme ci-dessus, je pense aussi qu'il serait mieux de la nommé ``isProdEnvironment()`` qui retourne un boolean : dans la quasi totalité des cas cela simplifierait la façon dont on écrit les vérifications.

2022-07-06 19:50 UTC, Steellgold commented on package.json
> +    "dev": "cross-env NODE_ENV=dev nodemon --exec ts-node ./src/Client.ts",
D'accord, je ne savais pas que cela était possible je vais modifier cela

2022-07-06 19:51 UTC, Bluzzi commented
C'est une bonne pratique de limiter un maximum le nombre de package utilisé pour facilité la maintenabilité du projet, cela évite de devoir réecrire du code si le package n'est plus maintenu dans le futur.

2022-07-06 19:59 UTC, Steellgold commented on src/Client.ts
> +    }
Corrigé ici: 
- https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/297eecb8d3c4f58419f47951953370819e901c13#diff-b7961e132a9ada7fe5b4cdec69198fc7e4fe506e45b5a7fe29f399a01c45ff53
- https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/297eecb8d3c4f58419f47951953370819e901c13#diff-2c041242038d17b059e2155adbd98b3e45727f4fb7b7375599802cf5f27c084d
- https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/297eecb8d3c4f58419f47951953370819e901c13#diff-180c5735ecff8a16c40585cbb8798b5ba3079432b260ad3f682fced03a8573cc

2022-07-24 00:53 UTC, Bluzzi requested changes

2022-07-24 00:53 UTC, Bluzzi commented on src/tasks/list/ActivityUpdate.ts
> +        if (!Client.instance.isProdEnvironment()) return;
Saut de ligne après cette ligne

2022-07-24 00:53 UTC, Bluzzi commented on src/events/list/MessageCreate.ts
> +        if (!Client.instance.isProdEnvironment()) return;
Saut de ligne après cette ligne

2022-07-24 17:30 UTC, Steellgold commented on src/events/list/MessageCreate.ts
> +        if (!Client.instance.isProdEnvironment()) return;
Fix: https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/7fc2360ed9e1578e15076bbbfa63196ccd45ef06

2022-07-24 17:30 UTC, Steellgold commented on src/tasks/list/ActivityUpdate.ts
> +        if (!Client.instance.isProdEnvironment()) return;
Fix: https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/7fc2360ed9e1578e15076bbbfa63196ccd45ef06

2022-07-24 18:58 UTC, Bluzzi approved these changes

2022-07-24 19:35 UTC, merged

2022-10-09 20:24 UTC, JedXDs commented
Les choses dont le bot n'a pas la permission tel que la création de channels ou autres qui servent pas a grand chose et qui font crash le bot

2022-10-09 22:03 UTC, Bluzzi commented
> Les choses dont le bot n'a pas la permission tel que la création de channels ou autres qui servent pas a grand chose et qui font crash le bot

Ce genre de chose peut maintenant être mis en place n'importe quand avec la nouvelle fonction.

Si tu ne veux pas le faire dans l'immédiat, tu peux ouvrir une issue pour listé ce qu'il faudrait faire.

2022-10-10 07:01 UTC, JedXDs commented
Il y a déjà une autre issue que j'avais déjà créé qui parle de ça. Il s'agit de la gestion du crash du bot quand il n'a pas la permission. Il faut maintenant utiliser la fonction que tu as rajouté ici au soucis de mon issue. Je me met pas tout de suite dessus.