Vote: Ajout d'émoji
Virtual-Royaume/Royaume-Discord-Bot pull request #80
Opened 2022-07-09 01:16 UTC by Steellgold

`npm run eslint`: :white_check_mark: 
Testé & Fonctionnel: :white_check_mark:

2022-07-09 07:40 UTC, Steellgold commented
L'idée aussi, pourquoi pas faire à l'aide de sous-commandes `/emoji list` qui dit quels émojis ont été proposées, ajoutée par qui ?

- `/emoji new` Pour proposer un nouvel émoji
- `/emoji del` Pour proposer de retirer un émoji

Ca amenerait quelque chose en plus pour que les membres puissent gérer leurs émojis sans forcément avoir quelqu'un a coté qu'on doit mentionner pour qu'il ajoute tel ou tel emoji

On pourrait faire la même chose avec les stickers, donc pourquoi pas par exemple `/stickers new`, `/stickers del`

2022-07-21 02:02 UTC, Steellgold commented
Des nouvelles @Bluzzi ?

2022-07-24 01:12 UTC, Bluzzi requested changes

2022-07-24 01:12 UTC, Bluzzi commented on src/commands/list/Emoji.ts
> +        else if (serverTier == "TIER_3") maxSize = 250;
Quelque chose comme :
```ts
const emojiForTier: Record<PremiumTier, number> = {
    "NONE": 50,
    "TIER_1": 100,
    "TIER_2": 150,
    "TIER_3": 250
};

const maxEmoji = emojiForTier[guild.premiumTier];
```

Serait plus clean, ça fait moins "hardcode"

2022-07-24 01:12 UTC, Bluzzi commented on src/commands/list/Emoji.ts
> +                 + " supprimez-en ou améliorer votre niveau à l'aide des boosts de serveur", "error")],
Pour les strings, utilise les ` à la place des double guillemet avec des +

2022-07-24 01:12 UTC, Bluzzi commented on src/commands/list/Emoji.ts
> +                 + " supprimez-en ou améliorer votre niveau à l'aide des boosts de serveur", "error")],
Même si ça fait long en width, on fera un systeme plus propre pour les messages dans le futur.

2022-07-24 01:12 UTC, Bluzzi commented on src/commands/list/Emoji.ts
> +        const emojiIdentifier = command.options.getString("name");
TypeScript pense que ses valeur peuvent être null, ajoute en second argument ``true`` :
```ts
const attachment = command.options.getAttachment("attachment", true);
const emojiIdentifier = command.options.getString("name", true);
```

2022-07-24 01:13 UTC, Bluzzi commented
Je peux avoir un screen (envoyé dans cette PR) de ce que cette commande donne sur Discord ? Etape par étape

2022-07-24 16:12 UTC, Steellgold commented on src/commands/list/Emoji.ts
> +                 + " supprimez-en ou améliorer votre niveau à l'aide des boosts de serveur", "error")],
> Même si ça fait long en width, on fera un systeme plus propre pour les messages dans le futur.

![image](https://user-images.githubusercontent.com/51505384/180656197-a5be5df1-6cce-46c3-b205-c753646acc1d.png)

Comment faire, car c'est pour ça que j'ai fait un saut de ligne avec un +, car ça me métait çà

2022-07-24 16:23 UTC, Steellgold commented on src/commands/list/Emoji.ts
> +        else if (serverTier == "TIER_3") maxSize = 250;
https://github.com/Virtual-Royaume/Royaume-Discord-Bot/pull/80#discussion_r928181007

2022-07-24 16:55 UTC, Bluzzi commented on src/commands/list/Emoji.ts
> +                 + " supprimez-en ou améliorer votre niveau à l'aide des boosts de serveur", "error")],
Laisse comme ça alors, on changera ça plus tard quand il y aura le nouveau systeme

2022-07-24 16:58 UTC, Steellgold commented on src/commands/list/Emoji.ts
> +                 + " supprimez-en ou améliorer votre niveau à l'aide des boosts de serveur", "error")],
Ok!

2022-07-24 16:59 UTC, Steellgold commented on src/commands/list/Emoji.ts
> +        const emojiIdentifier = command.options.getString("name");
Fix: https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/c41ea40af4f4336fd2eebd76e4805a974de97e31

2022-07-24 17:06 UTC, Steellgold commented on src/commands/list/Emoji.ts
> +        .addStringOption(option => option.setName("name").setDescription("Nom de l'émoji").setRequired(true));
Fix: https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/7c7aac1961dfb858cf09d723dceff9a175b58aa1

2022-07-24 17:09 UTC, Steellgold commented on resources/config/information.json
> +    },
Fix: https://github.com/Virtual-Royaume/Royaume-Discord-Bot/commit/27ad0f4f2bd24750b81655eefd2a50c6bbcae149

2022-07-24 17:27 UTC, Steellgold commented
> Je peux avoir un screen (envoyé dans cette PR) de ce que cette commande donne sur Discord ? Etape par étape

https://user-images.githubusercontent.com/51505384/180658953-e59d764d-cce3-4432-9cff-f4f600b4020a.mp4

2022-07-24 19:24 UTC, Bluzzi approved these changes

2022-07-24 19:33 UTC, merged